version: '3.3'

services:
  postgres:
    image: innost5/netology_postgres:latest
    ports:
      - 5432:5432

  redis:
    image: redis:alpine

  sqli:
    image: innost5/netology_app:latest
    depends_on:
      - postgres
      - redis
    ports:
      - 8080:8080
    command: |
      wait-for postgres:5432 -- python run.py
