version: '3.7'
services:
  sonarqube:
    image: sonarqube:8.6-community
    ports:
      - 9000:9000
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
  maven:
    image: maven:3-jdk-11
    volumes:
      - ./app:/app
    depends_on:
      - sonarqube
  ibdev:
    image: ibdev
    build: .
    ports:
      - 8080:8080