# Создаем build (билд, образ) docker, собирает сервисы, описанные в конфигурационных файлах
# docker-compose build

# Запускаем собранные сервисы image docker, если он не был создан, то автоматически будет создан
# docker-compose up

# Если какой-то из сервисов завершит работу, то остальные будут остановлены автоматически
# docker-compose up --abort-on-container-exit

# Запустит сервис application и выполнит внутри команду make install
# docker-compose run application make install

# А так мы можем запустить сервис и подключиться к нему с помощью bash
# docker-compose run application bash

# Останавливает и удаляет все сервисы, которые были запущены с помощью up
# docker-compose down

# Останавливает но не удаляет сервисы, запущенные с помощью up. Их можно запустить снова с помощью docker-compose start
# docker-compose stop

# Перезапускает все остановленные и запущенные сервисы
# docker-compose restart


#Версия docker
version: "3.9"

services:

  ubuntu:
    image: ubuntu  # что качаем, какую систему, сборку
    ports:         # какие порты открываем
      - 8080:8080
      - 80:80
      - 3001:3001
      

# позволяет создать последовательность вводимых команд    
    entrypoint: ["/bin/sh","-c"]  

# команды    
    command: 
      - |
       apt-get update -y
       apt-get install -y git
       apt-get install -y npm
       git clone --depth=1 https://github.com/ixartz/Eleventy-Starter-Boilerplate.git my-project-name
       cd my-project-name
       npm install
       npm run dev

